# Generated by Django 4.0.1 on 2022-02-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscad',
            name='dt_nascimento',
            field=models.DateTimeField(),
        ),
    ]
