# Generated by Django 4.0.1 on 2022-02-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_dadoscad_dt_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoscad',
            name='dt_nascimento',
        ),
    ]
