# Generated by Django 4.0.2 on 2022-04-30 18:48

import autoslug.fields
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cell', models.CharField(max_length=14, verbose_name='Celular')),
                ('postal_code', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=250, verbose_name='Endereço')),
                ('number', models.CharField(max_length=250, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=250, verbose_name='Complemento')),
                ('district', models.CharField(max_length=250, verbose_name='Bairro')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=250, verbose_name='Cidade')),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
