# Generated by Django 4.0.2 on 2022-05-01 14:00

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, verbose_name='CPF'),
        ),
    ]
